Repository tansuluu/Opentravel, pull requests merged in 2019-04, with the labels that each got.

#131 Chatting features are added
  pom.xml
  src/main/java/com/example/opentravel/config/WebSocketChatConfig.java
  src/main/java/com/example/opentravel/model/WebSocketChatMessage.java
Labels: 3 SPRINT, New feature

#134 handleWebSocketDisconnectListener added
  src/main/java/com/example/opentravel/config/SecurityConfiguration.java
  src/main/java/com/example/opentravel/config/WebSocketChatConfig.java
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/java/com/example/opentravel/controller/WebSocketChatController.java
  src/main/java/com/example/opentravel/service/WebSocketChatEventListener.java
  src/main/resources/static/css/style.css
  src/main/resources/static/js/script.js
  src/main/resources/templates/adminUsers.html
  src/main/resources/templates/home.html
  src/main/resources/templates/index.html
  src/main/resources/templates/newBlog.html
  src/test/java/com/example/opentravel/OpentravelApplicationTests.java
  src/test/java/com/example/opentravel/Sprint1.java
Labels: 3 SPRINT, Scaling a feature

#135 WebSocketEventListener added
  src/main/java/com/example/opentravel/config/SecurityConfiguration.java
  src/main/java/com/example/opentravel/config/WebSocketConfig.java
  src/main/java/com/example/opentravel/controller/ChatController.java
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/java/com/example/opentravel/controller/WebSocketChatController.java
  src/main/java/com/example/opentravel/controller/WebSocketEventListener.java
  src/main/java/com/example/opentravel/model/ChatMessage.java
  src/main/resources/static/css/main.css
  src/main/resources/static/js/main.js
  src/main/resources/static/js/script.js
  src/main/resources/templates/allPlaceS.html
  src/main/resources/templates/chat.html
  src/main/resources/templates/index.html
  src/test/java/com/example/opentravel/Sprint1.java
Labels: 3 SPRINT, Scaling a feature

#136 help.html was edited
  src/main/resources/application.properties
  src/main/resources/static/images/help.jpg
  src/main/resources/templates/help.html
  src/test/java/com/example/opentravel/Sprint1.java
Labels: 3 SPRINT, Scaling a feature

#137 Meder
  src/main/java/com/example/opentravel/config/SecurityConfiguration.java
  src/main/java/com/example/opentravel/config/WebSocketConfig.java
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/resources/application.properties
  src/main/resources/templates/chat.html
  src/main/resources/templates/help.html
Labels: 3 SPRINT, Scaling a feature

#138 Meder
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/java/com/example/opentravel/model/User.java
  src/main/java/com/example/opentravel/service/UserService.java
  src/main/resources/static/css/main.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/chat.html
Labels: bug

#144 Meder: One to many connection added
  src/main/java/com/example/opentravel/controller/PlaceController.java
  src/main/java/com/example/opentravel/controller/UserController.java
  src/main/java/com/example/opentravel/model/Place.java
  src/main/java/com/example/opentravel/model/PlaceComment.java
  src/main/java/com/example/opentravel/repository/PlaceRepository.java
  src/main/java/com/example/opentravel/repository/UserRepository.java
  src/main/java/com/example/opentravel/service/PlaceService.java
  src/main/java/com/example/opentravel/service/UserService.java
  src/main/java/com/example/opentravel/test/Sprint1.java
  src/main/resources/static/folderforindex/css/style.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/allPlaceS.html
  src/main/resources/templates/home.html
  src/main/resources/templates/places.html
  src/main/resources/templates/single-blog.html
  src/test/java/com/example/opentravel/BlogServiceTest.java
  src/test/java/com/example/opentravel/PlaceServiceTest.java
Labels: 3 SPRINT, New feature

#145 Nadyr: One to many connection added to blog model
  src/main/java/com/example/opentravel/model/Blog.java
  src/main/java/com/example/opentravel/repository/PlaceRepository.java
Labels: 3 SPRINT, Scaling a feature, TO DO USER STORY

#147 Blog model updated
  src/main/java/com/example/opentravel/controller/UserController.java
  src/main/java/com/example/opentravel/repository/BlogRepository.java
  src/main/java/com/example/opentravel/service/BlogService.java
  src/main/java/com/example/opentravel/service/UserService.java
  src/main/resources/templates/single-blog.html
  src/test/java/com/example/opentravel/BlogServiceTest.java
Labels: 3 SPRINT, bug

#148 Edilbey: html pages updated
  src/main/resources/templates/about.html
  src/main/resources/templates/allPlaceS.html
  src/main/resources/templates/blog.html
  src/main/resources/templates/chat.html
  src/main/resources/templates/gids.html
  src/main/resources/templates/newBlog.html
  src/main/resources/templates/newPlace.html
  src/main/resources/templates/places.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/single-blog.html
  src/main/resources/templates/updateBlog.html
  src/main/resources/templates/updatePlace.html
Labels: 3 SPRINT, invalid

#149 Nadyr: Pagination to place page added
  src/main/java/com/example/opentravel/controller/BlogController.java
  src/main/java/com/example/opentravel/controller/PlaceController.java
  src/main/java/com/example/opentravel/model/Blog.java
  src/main/java/com/example/opentravel/repository/BlogRepository.java
  src/main/java/com/example/opentravel/repository/PlaceRepository.java
  src/main/java/com/example/opentravel/service/BlogService.java
  src/main/java/com/example/opentravel/service/PlaceService.java
  src/main/resources/templates/allPlaceS.html
  src/main/resources/templates/blog.html
  src/main/resources/templates/home.html
  src/main/resources/templates/places.html
  src/main/resources/templates/single-blog.html
  src/test/java/com/example/opentravel/BlogServiceTest.java
  upload-dir/Djeti-Oguz-Kyrgyzstan.jpg
  upload-dir/Kyrgyzstan-Issyk-Kul-top-travel-places.jpg
  upload-dir/ddd.jpg
  upload-dir/downloadaaaaaaa.jpg
  upload-dir/downloadjmhfgf.jpg
  upload-dir/images.jpg
  upload-dir/kyrgyzstan-tash-rabat.jpg
  upload-dir/lakeofsarychelek3.jpg
  upload-dir/toktogul-d.jpg
  upload-dir/toktogul-dam.jpg
  upload-dir/toktogul.jpg
Labels: 3 SPRINT, New feature, Scaling a feature

#151 Meder:BlogServiceTest is edited, test for findByAuthor() is added
  src/test/java/com/example/opentravel/BlogServiceTest.java
  src/test/java/com/example/opentravel/PlaceServiceTest.java
Labels: 3 SPRINT

#154 Nadyr2: place comment added
  src/main/java/com/example/opentravel/controller/PlaceController.java
  src/main/java/com/example/opentravel/model/Place.java
  src/main/java/com/example/opentravel/model/PlaceComment.java
  src/main/java/com/example/opentravel/repository/PlaceCommentRepository.java
  src/main/java/com/example/opentravel/service/PlaceCommentService.java
  src/main/java/com/example/opentravel/test/Sprint1.java
  src/main/java/com/example/opentravel/test/Sprint2.java
  src/main/resources/static/css/main.css
  src/main/resources/templates/chat.html
  src/main/resources/templates/help.html
  src/main/resources/templates/home.html
  src/main/resources/templates/places.html
Labels: 3 SPRINT, New feature, TO DO USER STORY

#160 Elmira): help.html images was edited
  hs_err_pid16143.log
  src/main/resources/application.properties
  src/main/resources/static/images/guest2.png
  src/main/resources/static/images/guides.png
  src/main/resources/static/images/tourist.png
  src/main/resources/templates/help.html
  src/main/resources/templates/profile.html
Labels: 3 SPRINT, Scaling a feature

#161 Nadyr2: Comment blog service added
  src/main/java/com/example/opentravel/controller/BlogController.java
  src/main/java/com/example/opentravel/controller/PlaceController.java
  src/main/java/com/example/opentravel/model/CommentBlog.java
  src/main/java/com/example/opentravel/repository/CommentBlogRepository.java
  src/main/java/com/example/opentravel/repository/PlaceCommentRepository.java
  src/main/java/com/example/opentravel/service/CommentBlogService.java
  src/main/java/com/example/opentravel/service/PlaceCommentService.java
  src/main/java/com/example/opentravel/test/Sprint1.java
  src/main/java/com/example/opentravel/test/Sprint2.java
  src/main/resources/static/images/trash.png
  src/main/resources/templates/places.html
  src/main/resources/templates/single-blog.html
Labels: 3 SPRINT, New feature

#162 Meder: CommentBlogServiceTest is edited, testSave() is created
  src/test/java/com/example/opentravel/CommentBlogServiceTest.java
Labels: 3 SPRINT, Scaling a feature

#163 Nadyr2 : Write post to user page
  src/main/java/com/example/opentravel/controller/BlogController.java
  src/main/java/com/example/opentravel/controller/PlaceController.java
  src/main/java/com/example/opentravel/controller/UserController.java
  src/main/java/com/example/opentravel/model/Post.java
  src/main/java/com/example/opentravel/repository/PostRepository.java
  src/main/java/com/example/opentravel/service/PostService.java
  src/main/resources/templates/places.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/single-blog.html
Labels: 3 SPRINT, Scaling a feature

#164 Meder: PlaceCommentServiceTest is added
  src/test/java/com/example/opentravel/CommentBlogServiceTest.java
  src/test/java/com/example/opentravel/PlaceCommentServiceTest.java
Labels: 3 SPRINT, Scaling a feature

#165 Part of Sprint3
  src/main/java/com/example/opentravel/test/Sprint1.java
  src/main/java/com/example/opentravel/test/Sprint2.java
  src/main/java/com/example/opentravel/test/Sprint3.java
Labels: 3 SPRINT

#166 About page
  src/main/resources/templates/about.html
  src/main/resources/templates/gids.html
Labels: 3 SPRINT

#168 about us button was edited
  src/main/resources/templates/about.html
Labels: 3 SPRINT

#169 Edil2
  src/main/resources/templates/about.html
  src/main/resources/templates/newPlace.html
Labels: 3 SPRINT

#171 CHATING UPDATED
  src/main/java/com/example/opentravel/controller/ChatController.java
  src/main/java/com/example/opentravel/controller/WebSocketEventListener.java
  src/main/java/com/example/opentravel/model/ChatMessage.java
  src/main/resources/static/js/main.js
Labels: 3 SPRINT, Scaling a feature

#173 Tansuluu
  src/main/java/com/example/opentravel/controller/BlogController.java
  src/main/java/com/example/opentravel/service/BlogService.java
  src/main/java/com/example/opentravel/service/CommentBlogService.java
  src/main/java/com/example/opentravel/test/Sprint1.java
  src/main/java/com/example/opentravel/test/Sprint3.java
  src/main/resources/templates/allPlaceS.html
  src/main/resources/templates/single-blog.html
  src/test/java/com/example/opentravel/PlaceCommentServiceTest.java
Labels: 4 SPRINT, New feature

#174 Meder: PostServiceTest is added
  src/main/java/com/example/opentravel/controller/UserController.java
  src/main/resources/application.properties
  src/test/java/com/example/opentravel/PostServiceTest.java
Labels: 4 SPRINT

#175 Elmira): profile.html button was edited
  src/main/java/com/example/opentravel/controller/UserController.java
  src/main/java/com/example/opentravel/test/Sprint1.java
  src/main/java/com/example/opentravel/test/Sprint2.java
  src/main/java/com/example/opentravel/test/Sprint3.java
  src/main/resources/application.properties
  src/main/resources/static/folderforprofile/css/style.css
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateUser.html
Labels: 4 SPRINT

#177 Nadyr2: Comment update to blog added
  src/main/java/com/example/opentravel/controller/BlogController.java
  src/main/java/com/example/opentravel/model/CommentBlog.java
  src/main/java/com/example/opentravel/service/CommentBlogService.java
  src/main/resources/templates/places.html
  src/main/resources/templates/single-blog.html
Labels: 4 SPRINT, New feature

#178 Edil2: HomeInRussian.html created
  src/main/resources/templates/about.html
  src/main/resources/templates/homeInRussian.html
Labels: 4 SPRINT

#179 Update homeInRussian.html
  src/main/resources/templates/homeInRussian.html
Labels: 4 SPRINT

#181 aboutRus.html page was added
  src/main/java/com/example/opentravel/model/CommentBlog.java
  src/main/resources/templates/aboutRus.html
Labels: 4 SPRINT

#183 Nadyr2: Put like to blog
  src/main/java/com/example/opentravel/controller/LikesController.java
  src/main/java/com/example/opentravel/model/Likes.java
  src/main/java/com/example/opentravel/repository/LikesRepository.java
  src/main/java/com/example/opentravel/service/BlogService.java
  src/main/java/com/example/opentravel/service/LikesService.java
  src/main/resources/templates/single-blog.html
Labels: 4 SPRINT

#184 Elmira) : aboutRus.html's content was translated
  src/main/resources/templates/aboutRus.html
Labels: 4 SPRINT

#193 Nadyr2: Put like to place
  src/main/java/com/example/opentravel/controller/LikesController.java
  src/main/java/com/example/opentravel/model/Likes.java
  src/main/java/com/example/opentravel/service/PlaceService.java
  src/main/resources/templates/places.html
  src/main/resources/templates/single-blog.html
Labels: 4 SPRINT, Scaling a feature

#194 Meder: views of places
  src/main/java/com/example/opentravel/controller/BlogController.java
  src/main/java/com/example/opentravel/controller/PlaceController.java
  src/main/java/com/example/opentravel/service/BlogService.java
  src/main/java/com/example/opentravel/service/PlaceService.java
Labels: 4 SPRINT, New feature, Scaling a feature

#195 Meder: Favorite Repository and Service added
  src/main/java/com/example/opentravel/controller/FavoriteController.java
  src/main/java/com/example/opentravel/model/Favorite.java
  src/main/java/com/example/opentravel/repository/FavoriteRepository.java
  src/main/java/com/example/opentravel/service/FavoriteService.java
  src/main/resources/application.properties
  src/main/resources/static/folderforindex/css/style.css
  src/main/resources/templates/places.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/single-blog.html
  src/main/resources/templates/updateUser.html
Labels: 4 SPRINT, New feature, Scaling a feature

#196 Edil2: Update homeInRussian.html
  src/main/resources/templates/homeInRussian.html
Labels: 4 SPRINT, Scaling a feature

#197 PlaceCommentServiceTest and CommentBlogServiceTest are edited
  src/test/java/com/example/opentravel/CommentBlogServiceTest.java
  src/test/java/com/example/opentravel/PlaceCommentServiceTest.java
Labels: 4 SPRINT, Unit test

#198 Meder: assigne to favorite
  src/main/java/com/example/opentravel/controller/FavoriteController.java
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/java/com/example/opentravel/controller/UserController.java
  src/main/java/com/example/opentravel/repository/FavoriteRepository.java
  src/main/java/com/example/opentravel/service/FavoriteService.java
  src/main/java/com/example/opentravel/service/PlaceService.java
  src/main/resources/templates/allPlaceS.html
  src/main/resources/templates/places.html
  src/main/resources/templates/profile.html
Labels: 4 SPRINT, New feature, Scaling a feature

#199 Update homeInRussian.html
  src/main/resources/templates/homeInRussian.html
Labels: 4 SPRINT, invalid

#200 errors were fixed
  src/main/resources/application.properties
  src/main/resources/templates/aboutRus.html
  src/main/resources/templates/help.html
  src/main/resources/templates/profile.html
Labels: 4 SPRINT, bug, invalid

#201 Meder: Translation started
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/resources/static/images/eng.jpg
  src/main/resources/static/images/eng.png
  src/main/resources/static/images/rus.png
  src/main/resources/templates/aboutRus.html
  src/main/resources/templates/home.html
  src/main/resources/templates/homeInRussian.html
Labels: 4 SPRINT, New feature, Scaling a feature

#203 Edil2: Create helpRussian.html
  src/main/resources/templates/helpRussian.html
Labels: 4 SPRINT, Scaling a feature

#204 Meder: Translation started
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/resources/static/datatables-plugins/dataTables.bootstrap.css
  src/main/resources/static/datatables-plugins/dataTables.bootstrap.js
  src/main/resources/static/datatables-plugins/dataTables.bootstrap.min.js
  src/main/resources/static/datatables-plugins/index.html
  src/main/resources/static/datatables-responsive/dataTables.responsive.css
  src/main/resources/static/datatables-responsive/dataTables.responsive.js
  src/main/resources/static/datatables-responsive/dataTables.responsive.scss
  src/main/resources/static/datatables/css/dataTables.bootstrap.css
  src/main/resources/static/datatables/css/dataTables.bootstrap.min.css
  src/main/resources/static/datatables/css/dataTables.bootstrap4.css
  src/main/resources/static/datatables/css/dataTables.bootstrap4.min.css
  src/main/resources/static/datatables/css/dataTables.foundation.css
  src/main/resources/static/datatables/css/dataTables.foundation.min.css
  src/main/resources/static/datatables/css/dataTables.jqueryui.css
  src/main/resources/static/datatables/css/dataTables.jqueryui.min.css
  src/main/resources/static/datatables/css/dataTables.material.css
  src/main/resources/static/datatables/css/dataTables.material.min.css
  src/main/resources/static/datatables/css/dataTables.semanticui.css
  src/main/resources/static/datatables/css/dataTables.semanticui.min.css
  src/main/resources/static/datatables/css/dataTables.uikit.css
  src/main/resources/static/datatables/css/dataTables.uikit.min.css
  src/main/resources/static/datatables/css/jquery.dataTables.css
  src/main/resources/static/datatables/css/jquery.dataTables.min.css
  src/main/resources/static/datatables/css/jquery.dataTables_themeroller.css
  src/main/resources/static/datatables/images/Sorting icons.psd
  src/main/resources/static/datatables/images/favicon.ico
  src/main/resources/static/datatables/images/sort_asc.png
  src/main/resources/static/datatables/images/sort_asc_disabled.png
  src/main/resources/static/datatables/images/sort_both.png
  src/main/resources/static/datatables/images/sort_desc.png
  src/main/resources/static/datatables/images/sort_desc_disabled.png
  src/main/resources/static/datatables/js/dataTables.bootstrap.js
  src/main/resources/static/datatables/js/dataTables.bootstrap.min.js
  src/main/resources/static/datatables/js/dataTables.bootstrap4.js
  src/main/resources/static/datatables/js/dataTables.bootstrap4.min.js
  src/main/resources/static/datatables/js/dataTables.foundation.js
  src/main/resources/static/datatables/js/dataTables.foundation.min.js
  src/main/resources/static/datatables/js/dataTables.jqueryui.js
  src/main/resources/static/datatables/js/dataTables.jqueryui.min.js
  src/main/resources/static/datatables/js/dataTables.material.js
  src/main/resources/static/datatables/js/dataTables.material.min.js
  src/main/resources/static/datatables/js/dataTables.semanticui.js
  src/main/resources/static/datatables/js/dataTables.semanticui.min.js
  src/main/resources/static/datatables/js/dataTables.uikit.js
  src/main/resources/static/datatables/js/dataTables.uikit.min.js
  src/main/resources/static/datatables/js/jquery.dataTables.js
  src/main/resources/static/datatables/js/jquery.dataTables.min.js
  src/main/resources/static/datatables/js/jquery.js
  src/main/resources/templates/adminUsers.html
  src/main/resources/templates/home.html
  src/main/resources/templates/homeInRussian.html
Labels: 4 SPRINT, New feature, Scaling a feature

#205 Edil2: Update helpRussian.html
  src/main/resources/templates/helpRussian.html
Labels: 4 SPRINT, Scaling a feature

#206 Meder: Data table is adding
  src/main/java/com/example/opentravel/controller/AdminController.java
  src/main/java/com/example/opentravel/controller/UserController.java
  src/main/resources/templates/adminUsers.html
Labels: 4 SPRINT, Scaling a feature

#207 Elmira):Translated page of profile added
  src/main/java/com/example/opentravel/config/WebSocketConfig.java
  src/main/java/com/example/opentravel/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/profileRussian.html
Labels: 4 SPRINT, Scaling a feature

#209 Meder: LikesServiceTest is added
  src/test/java/com/example/opentravel/FavoriteServiceTest.java
  src/test/java/com/example/opentravel/LikesServiceTest.java
Labels: 4 SPRINT, Unit test

#210 Elmira): profile page translated
  src/main/resources/application.properties
  src/main/resources/templates/profileRussian.html
Labels: 4 SPRINT, Scaling a feature

#211 Edil2: Update helpRussian.html
  src/main/resources/templates/helpRussian.html
Labels: 4 SPRINT, Scaling a feature

#212 Nadyr2: Admin page addded
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/java/com/example/opentravel/model/ContactMessage.java
  src/main/resources/templates/about.html
  src/main/resources/templates/adminBlogs.html
  src/main/resources/templates/help.html
  src/main/resources/templates/home.html
  src/main/resources/templates/homeInRussian.html
  src/main/resources/templates/russian/aboutRus.html
Labels: 4 SPRINT, New feature, Scaling a feature

#213 Nadyr2: Contact Message function added
  src/main/java/com/example/opentravel/controller/AdminController.java
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/java/com/example/opentravel/repository/ContactMessageRepository.java
  src/main/java/com/example/opentravel/service/ContactMessageService.java
  src/main/resources/application.properties
  src/main/resources/templates/about.html
  src/main/resources/templates/home.html
Labels: 4 SPRINT, New feature, Scaling a feature

#221 Profile page errors and translations
  src/main/resources/application.properties
  src/main/resources/templates/profileRussian.html
  src/main/resources/templates/russian/aboutRus.html
Labels: 4 SPRINT, Scaling a feature

#224 Nadyr2: Reply to contact messages added
  src/main/java/com/example/opentravel/controller/AdminController.java
  src/main/java/com/example/opentravel/service/ContactMessageService.java
  src/main/resources/templates/adminContact.html
Labels: 4 SPRINT, New feature, Scaling a feature

#225 Zarlyk: Changed full architecture
  src/main/java/com/example/opentravel/test/Main.java
  src/main/java/com/example/opentravel/test/Sprint1.java
  src/main/java/com/example/opentravel/test/Sprint2.java
  src/main/java/com/example/opentravel/test/Sprint3.java
  src/main/java/com/example/opentravel/test/Sprint4.java
  src/main/resources/templates/blog.html
  src/main/resources/templates/gids.html
  src/main/resources/templates/updateBlog.html
Labels: 4 SPRINT, Acceptance test

#226 logo was added
  src/main/resources/application.properties
  src/main/resources/static/images/logo2.png
  src/main/resources/static/images/newlogo.png
  src/main/resources/templates/home.html
Labels: 4 SPRINT

#227 Nadyr2: Contact message form working
  pom.xml
  src/main/java/com/example/opentravel/OpentravelApplication.java
  src/main/java/com/example/opentravel/controller/AdminController.java
  src/main/java/com/example/opentravel/service/ContactMessageService.java
  src/main/java/com/example/opentravel/test/Main.java
  src/main/java/com/example/opentravel/test/Sprint1.java
  src/main/java/com/example/opentravel/test/Sprint2.java
  src/main/java/com/example/opentravel/test/Sprint3.java
  src/main/java/com/example/opentravel/test/Sprint4.java
  src/main/resources/templates/adminContact.html
  src/main/resources/templates/single-blog.html
  src/test/java/com/example/opentravel/CommentBlogServiceTest.java
  src/test/java/com/example/opentravel/PlaceCommentServiceTest.java
Labels: 4 SPRINT, invalid

#228 ContactMessageServiceTest is added
  src/test/java/com/example/opentravel/ContactMessageServiceTest.java
Labels: 4 SPRINT, Scaling a feature

#229 Nadyr2:multi lang adding
  src/main/java/com/example/opentravel/controller/LoginController.java
  src/main/java/com/example/opentravel/controller/MainController.java
  src/main/resources/templates/about.html
  src/main/resources/templates/allPlaceS.html
  src/main/resources/templates/blog.html
  src/main/resources/templates/gids.html
  src/main/resources/templates/helpRussian.html
  src/main/resources/templates/login.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/russian/aboutRus.html
  src/main/resources/templates/single-blog.html
Labels: 4 SPRINT, Scaling a feature

#230 Nadyr2: multi lang adding
  src/main/resources/templates/allPlaceS.html
  src/test/java/com/example/opentravel/CommentBlogServiceTest.java
  src/test/java/com/example/opentravel/PlaceCommentServiceTest.java
Labels: 4 SPRINT

#231 Nadyr2: Bugs are resolved
  src/main/resources/static/folderforadmin/css/theme.css
  src/main/resources/templates/blog.html
  src/main/resources/templates/gids.html
Labels: 4 SPRINT

#232 error on logo was fixed
  src/main/resources/templates/russian/aboutRus.html
Labels: 4 SPRINT

#233 all the errors are edited
  src/test/java/com/example/opentravel/CommentBlogServiceTest.java
  src/test/java/com/example/opentravel/PlaceCommentServiceTest.java
Labels: 4 SPRINT, Unit test
